# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Prepare to publish
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS_BASE64 }}
        run: |
          echo "${{ secrets.GPG_KEY_CONTENTS_BASE64 }}" | base64 --decode > secring.gpg

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean jar fatJar publish -Psigning.secretKeyRingFile=secring.gpg -Psigning.keyId=${{secrets.SIGNING_KEYID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}}
        env:
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          DEVELOPER_ID: ${{secrets.DEVELOPER_ID}}
          DEVELOPER_NAME: ${{secrets.DEVELOPER_NAME}}
          DEVELOPER_EMAIL: ${{secrets.DEVELOPER_EMAIL}}